apiVersion: v1
kind: Service
metadata:
  name: load-web
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: load-crime
spec:
  type: LoadBalancer
  selector:
    app: scenecrimeapi
  ports:
    - port: 81
      targetPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: load-lawenforcement
spec:
  type: LoadBalancer
  selector:
    app: crimescene
  ports:
    - port: 82
      targetPort: 80
      protocol: TCP
